feat: improve auth functionalities
NaucMeIT/web pull request #400
Opened 2024-08-24 01:58 UTC by devodii

- add email package with resend helper
- support for credential authentication
- implement password hashing with bcrypt

2024-08-26 20:08 UTC, NaucMeIT requested changes
**blocker:** We shouldn't add EffectTS as part of this ticket. It's not well architected and would need another major rewrite.

2024-08-26 20:08 UTC, NaucMeIT commented on apps/coursition/src/app/api/auth/[...nextauth]/auth-options.ts
> +      catch: () => Effect.fail('user not found'),
**blocker:** We don't handle invalid password and failing effect like this is not correct way. We should use Expected Error (mentioned in review above).

2024-08-26 20:08 UTC, NaucMeIT commented on apps/coursition/src/components/googleSignIn.tsx
> +  )
**nitpick:** We should use server login (that works even without JS. But we'll handle it with Auth.js v5.
https://authjs.dev/getting-started/session-management/login

```suggestion
  return (
    <form
      action={async () => {
        "use server"
        await signIn("google", { callbackUrl: "/" })
      }}
    >
      <button type="submit">Sign in</button>
    </form>
  )
```

2024-08-26 20:08 UTC, NaucMeIT commented on apps/legacy_nmit/pnpm-lock.yaml
**blocker:** You shouldn't delete anything in `legacy_nmit`, it's old version of NMIT and is not part of the ticket.

2024-08-28 21:03 UTC, BleedingDev requested changes

2024-08-28 21:03 UTC, BleedingDev commented on libs/email/src/index.ts
> +import { Effect } from 'effect'
Why is there still Effect? Please remove it completely, including from `package.json`.

2024-08-28 21:03 UTC, BleedingDev commented on package.json
> +    "effect": "^3.6.5",
Please remove Effect.

2024-08-30 12:38 UTC, merged